= Ling Yan Hao - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: REstaurant Manager

---

== Overview

REstaurant Manager (REM) is a desktop application that turns your restaurant into a smart restaurant. It is meant for restaurant owners to manage their member base, staff, bookings and food inventory.

== Summary of contributions

* Code contributed: (insert link)

* *Major enhancement*: added *booking feature*
** What it does: allows the user to manage bookings. The system will reject new bookings and suggest better alternative timeslots if the restaurant hits capacity.
** Justification: When a restaurant needs to manage a large number of bookings, the restaurant can be overbooked. 
** Highlights: This feature affects the existing delete and edit commands for members as changing a member's personal details requires a corresponding update in the booking panel. It required a significant restructuring of the `Model` component. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: (insert enchancement)

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management: (todo)

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=booking]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=model]
include::../DeveloperGuide.adoc[tag=ds]
include::../DeveloperGuide.adoc[tag=editcmd]
